### ISSUE TITLE
There was some errors with your submission   /  could not find a ready tiller pod

### ISSUE THREAD

**Issue by vielmetti** [harbur/kubernetic-issues#17]
I'm working my way through the tutorial at 

https://docs.kubernetic.com/pods.html

at "Go to the tutorial chart repo and run the pod-hello-world chart."

When I do so I get this error message:

There was some errors with your submission 
   could not find a ready tiller pod

![screen shot 2017-03-03 at 4 40 59 pm](https://cloud.githubusercontent.com/assets/35047/23569995/3c1a39b6-0030-11e7-90e2-07205311cffd.png)

**Comment by vielmetti** [comment]
I'm following the instructions about installing `helm` at https://github.com/kubernetes/helm/blob/master/docs/quickstart.md but still not getting joy.

**Comment by spiddy** [comment]
This is because your tiller is not ready yet.

When helm is installed, it installs a server-side component (deployment) on `kube-system`. This needs to be ready to receive the requests before Kubernetic can send the chart deployments.

Go to kube-system and check tiller status

```
kubectl get pod --namespace=kube-system -l name=tiller
NAME                             READY     STATUS    RESTARTS   AGE
tiller-deploy-2923173008-3gpjq   1/1       Running   0          5h
```

When that is ready you should be able to deploy charts.

**Comment by vielmetti** [comment]
This looks like a problem with helm - as when I go to the command line to try this out I also get

```
$ helm ls
Error: could not find a ready tiller pod
```

I'll work my way upstream.

**Comment by vielmetti** [comment]
Aha, 

```
$ kubectl get pod --namespace=kube-system -l name=tiller
NAME                             READY     STATUS              RESTARTS   AGE
tiller-deploy-2654728925-j2zvk   0/1       ContainerCreating   0          17m
```

**Comment by vielmetti** [comment]
The upstream for reference is https://github.com/kubernetes/helm/issues/2064

**Comment by vielmetti** [comment]
As remedied upstream, I'll note that I ran `minikube addons enable registry-creds` which seemed to address the problem of "no credentials on this request".

Thanks for the help @spiddy - hopefully this will be useful to a next person who runs into this. Closing as the problem is resolved.

**Comment by ratnamkamila** [comment]
HI NOw the same problem we are facing tiller pod is not ready what should we do
