### ISSUE TITLE
After adding charts, browser crash

### ISSUE THREAD

**Issue by vielmetti** [harbur/kubernetic-issues#18]
I added https://github.com/kubernetes/charts.git as a source of charts, and now I get this browser error crash and the system is locked up.

![screen shot 2017-03-03 at 9 05 50 pm](https://cloud.githubusercontent.com/assets/35047/23575071/6f675eb4-0055-11e7-8cf3-1dc444e3d106.png)

My intent was to add the Helm charts to the system, but clearly I did something wrong.

**Comment by vielmetti** [comment]
The recovery was to delete the offending lines from config.json, but I'm puzzled still by how to get access to the default collection of Helm charts.

**Comment by spiddy** [comment]
This is a bug, that was triggered by Spark chart containing twice the "home" tag in its Chart.yaml.

Kubernetic is parsing the Charts to get the information, but needs to do better handling on errors as these. In the meantime go to `~/.kubernetic/repositories/REPO_ID/spark/Chart.yaml` and delete one of the two `home` tags.

I'll send them a PR to fix that and leave this issue open to improve the error handling in Kubernetic.

**Comment by spiddy** [comment]
As a sidenote Kubernetic will soon get remote helm repos (such as stable at https://kubernetes-charts.storage.googleapis.com/)

**Comment by spiddy** [comment]
Fixed for v0.7.0.

YAML duplicate tags will no long through exceptions, but be merged and parsed properly
Also Chart.yaml that fail will not crash the system but will be excluded
