### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by mirague** [harbur/kubernetic-issues#26]
The client downloaded from the website is marked version `0.7`, when trying to update the application through "Check for updates" it just informs an update is being downloaded in the background and I'll be notified when it's ready to install. Nothing happens.

What's the status of this project?

**Comment by spiddy** [comment]
Hi,

thanks for checking out. Yes the project is live and kicking! Recently did the first meetup presentation [here](https://www.meetup.com/Kubernetes-Barcelona/events/238798277/). The new version will be published on the site soon.

The "Check for updates" is fairly new feature, will review the status and get back here with feedback.

**Comment by spiddy** [comment]
v0.8.0 is now released properly and published on website.

**Comment by Platzii** [comment]
Any upcoming updates?
