### ISSUE TITLE
visual problem on labels

### ISSUE THREAD

**Issue by pineda89** [harbur/kubernetic-issues#8]
Hello,
i found a problem

![image](https://cloud.githubusercontent.com/assets/7601756/21186349/88fcf1e2-c214-11e6-89ef-4e8e75946c3c.png)

As you can see in the image, not all labels has been showed on my screen. If I change my resolution, less labels will be showed!

My pc specs:
* Ubuntu 16.04 LTS
* Resolution 1920x1080
* kubernetic version 4

thanks!!

**Comment by spiddy** [comment]
confirmed, this will be resolved on next release

**Comment by spiddy** [comment]
Fixed, now labels will be dropped in next line if they don't fit.
